import { StyleSheet } from 'react-native';
import { Fonts } from '../../theme';

/**
 * ParkingScreen styles — extracted from the 500-line inline StyleSheet.
 * All styles are static and don't depend on component state.
 */
export const parkingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#101319',
  },

  // Custom Header - Fixed Position
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    backgroundColor: 'rgba(16, 19, 25, 0.9)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.4,
    shadowRadius: 48,
    elevation: 24,
    paddingHorizontal: 24,
    paddingVertical: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileImage: {
    width: 40,
    height: 40,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(134, 148, 137, 0.2)',
  },
  brandName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#59de9b',
    fontFamily: Fonts.headline,
    letterSpacing: -0.5,
  },
  walletBadge: {
    backgroundColor: '#191c21',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(134, 148, 137, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  walletAmount: {
    fontSize: 16,
    fontWeight: '700',
    color: '#59de9b',
    fontFamily: Fonts.headline,
    letterSpacing: -0.3,
  },

  // Main Content Area
  contentArea: {
    flex: 1,
    paddingTop: 110,
    paddingBottom: 120,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },

  // Active Parking Session Banner
  activeSessionBanner: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#1d2025',
    borderRadius: 12,
    padding: 24,
    marginBottom: 40,
    borderLeftWidth: 4,
    borderLeftColor: '#59de9b',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  sessionIcon: {
    position: 'absolute',
    top: 0,
    right: 0,
    padding: 32,
    opacity: 0.1,
  },
  sessionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  sessionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#59de9b',
  },
  statusText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#59de9b',
    fontFamily: Fonts.label,
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  sessionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#e1e2ea',
    fontFamily: Fonts.headline,
  },
  sessionSubtitle: {
    fontSize: 14,
    color: '#bccabe',
    fontFamily: Fonts.body,
    marginTop: 4,
  },
  sessionTimer: {
    alignItems: 'flex-end',
  },
  timerText: {
    fontSize: 22,
    fontWeight: '800',
    color: '#ffd887',
    fontFamily: Fonts.headline,
    letterSpacing: 1,
  },
  rateText: {
    fontSize: 12,
    color: '#bccabe',
    fontFamily: Fonts.body,
    marginTop: 4,
  },
  sessionActions: {
    flexDirection: 'row',
    gap: 8,
  },
  qrButton: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(134, 148, 137, 0.2)',
    alignItems: 'center',
  },
  qrButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#e1e2ea',
    fontFamily: Fonts.label,
  },
  endButton: {
    flex: 1,
    backgroundColor: '#ff5a4c',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#ff5a4c',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  endButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#e1e2ea',
    fontFamily: Fonts.label,
  },

  // Parking Lots Section
  parkingSection: {
    marginBottom: 40,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#e1e2ea',
    fontFamily: Fonts.headline,
    letterSpacing: -0.3,
  },
  refreshTime: {
    fontSize: 10,
    fontWeight: '700',
    color: '#59de9b',
    fontFamily: Fonts.label,
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  lotsList: {
    gap: 16,
  },
  lotCard: {
    backgroundColor: '#1d2025',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(134, 148, 137, 0.05)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
  },
  lotHeader: {
    padding: 20,
  },
  lotInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  lotDetails: {
    flex: 1,
  },
  lotName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#e1e2ea',
    fontFamily: Fonts.headline,
  },
  lotLocation: {
    fontSize: 14,
    color: '#bccabe',
    fontFamily: Fonts.body,
    marginTop: 4,
  },
  lotPricing: {
    alignItems: 'flex-end',
  },
  priceAmount: {
    fontSize: 20,
    fontWeight: '800',
    color: '#59de9b',
    fontFamily: Fonts.headline,
  },
  priceLabel: {
    fontSize: 12,
    color: '#bccabe',
    fontFamily: Fonts.body,
    marginTop: 2,
  },
  availabilityBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  progressBar: {
    flex: 1,
    height: 4,
    backgroundColor: '#32353b',
    borderRadius: 2,
  },
  progressFill: {
    height: 4,
    borderRadius: 2,
  },
  availabilityText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#bccabe',
    fontFamily: Fonts.label,
  },

  // Spot Selection Grid
  spotSelection: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(134, 148, 137, 0.1)',
  },
  spotSelectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#bccabe',
    fontFamily: Fonts.label,
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    marginBottom: 16,
  },
  spotGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  spotButton: {
    width: 44,
    height: 36,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
  },
  spotAvailable: {
    backgroundColor: '#191c21',
    borderColor: 'rgba(134, 148, 137, 0.2)',
  },
  spotSelected: {
    backgroundColor: 'rgba(89, 222, 155, 0.1)',
    borderColor: '#59de9b',
  },
  spotOccupied: {
    backgroundColor: 'rgba(255, 90, 76, 0.1)',
    borderColor: 'rgba(255, 90, 76, 0.2)',
    opacity: 0.5,
  },
  spotText: {
    fontSize: 12,
    fontWeight: '700',
    fontFamily: Fonts.label,
  },
  spotTextAvailable: {
    color: '#bccabe',
  },
  spotTextSelected: {
    color: '#59de9b',
  },
  spotTextOccupied: {
    color: '#ff5a4c',
  },
  spotLegend: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 16,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 3,
    borderWidth: 1.5,
  },
  legendText: {
    fontSize: 12,
    color: '#bccabe',
    fontFamily: Fonts.body,
  },

  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  modalContent: {
    backgroundColor: '#101319',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    padding: 24,
    paddingBottom: 40,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#e1e2ea',
    fontFamily: Fonts.headline,
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 18,
    color: '#bccabe',
    fontFamily: Fonts.body,
    marginBottom: 20,
  },
  modalInfo: {
    backgroundColor: '#191c21',
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
  },
  modalButton: {
    backgroundColor: '#59de9b',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 24,
    alignItems: 'center',
    shadowColor: '#59de9b',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#101319',
    fontFamily: Fonts.label,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cancelButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(134, 148, 137, 0.2)',
    alignItems: 'center',
    marginTop: 8,
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#e1e2ea',
    fontFamily: Fonts.label,
  },

  // QR Modal
  qrModalContent: {
    backgroundColor: '#101319',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    padding: 24,
    paddingBottom: 40,
    alignItems: 'center',
  },
  qrCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
  },
  qrTitle: {
    color: '#666',
    fontSize: 12,
    textAlign: 'center',
    letterSpacing: 1,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 8,
    fontFamily: Fonts.label,
  },
  qrCode: {
    fontFamily: 'Courier',
    fontSize: 14,
    color: '#333',
    fontWeight: '700',
    letterSpacing: 1,
    textAlign: 'center',
  },
  qrDescription: {
    color: '#bccabe',
    textAlign: 'center',
    fontFamily: Fonts.body,
  },
});
