import { StyleSheet, Dimensions } from 'react-native';
import { Fonts, DarkColors as T } from '../../theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const ADDIS_NOIR = {
  ink: '#0B0D11',
  surface: '#131720',
  lift: '#1B2030',
  rim: '#242B3D',
  gold: '#D4AF37',
  cyan: '#00F5FF',
  glass: 'rgba(255, 255, 255, 0.05)',
  edge: 'rgba(255, 255, 255, 0.08)',
};

export const parkingStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: ADDIS_NOIR.ink },

  // 🏙️ Map Header
  mapHeader: {
    height: 180,
    backgroundColor: ADDIS_NOIR.surface,
    paddingTop: 50,
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: ADDIS_NOIR.edge,
  },
  mapGradient: { ...StyleSheet.absoluteFillObject },
  mapMeta: { zIndex: 10 },
  hotspotBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 245, 255, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.2)',
    marginBottom: 8,
  },
  pulseDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: ADDIS_NOIR.cyan,
    marginRight: 6,
  },
  hotspotText: { color: ADDIS_NOIR.cyan, fontSize: 10, fontFamily: Fonts.bold, letterSpacing: 0.5 },
  mapTitle: { color: '#FFF', fontSize: 28, fontFamily: Fonts.bold },
  headerWallet: { position: 'absolute', bottom: 20, right: 20, alignItems: 'flex-end', zIndex: 10 },
  walletLabel: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 9,
    fontFamily: Fonts.bold,
    letterSpacing: 1,
  },
  walletValue: { color: ADDIS_NOIR.gold, fontSize: 18, fontFamily: Fonts.bold },

  // 🏎️ Cockpit
  cockpitCard: { margin: 16, borderRadius: 32, overflow: 'hidden', elevation: 10 },
  cockpitGradient: { padding: 24 },
  cockpitHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  cockpitBrand: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  cockpitTitle: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 10,
    fontFamily: Fonts.bold,
    letterSpacing: 1,
  },
  cockpitSub: { color: '#FFF', fontSize: 16, fontFamily: Fonts.bold, marginTop: 2 },
  cockpitQrBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cockpitMain: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 },
  timerBlock: { flex: 1 },
  timerVal: { color: ADDIS_NOIR.gold, fontSize: 32, fontFamily: Fonts.bold },
  timerLabel: { color: 'rgba(255,255,255,0.4)', fontSize: 9, fontFamily: Fonts.bold, marginTop: 4 },
  fareBlock: { flex: 1, alignItems: 'flex-end' },
  fareVal: { color: '#FFF', fontSize: 32, fontFamily: Fonts.bold },
  fareLabel: { color: 'rgba(255,255,255,0.4)', fontSize: 9, fontFamily: Fonts.bold, marginTop: 4 },
  cockpitEndBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF',
    paddingVertical: 16,
    borderRadius: 16,
    gap: 8,
  },
  cockpitEndText: { color: '#0B0D11', fontSize: 14, fontFamily: Fonts.bold, letterSpacing: 0.5 },

  // 🅿️ Listings
  scrollView: { flex: 1 },
  scrollContent: { paddingBottom: 40 },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 24,
    marginBottom: 16,
  },
  sectionTitle: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 11,
    fontFamily: Fonts.bold,
    letterSpacing: 1,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: ADDIS_NOIR.surface,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ADDIS_NOIR.edge,
  },
  filterText: { color: 'rgba(255,255,255,0.4)', fontSize: 10, fontFamily: Fonts.bold },
  lotsList: { paddingHorizontal: 16, gap: 12 },

  // Lot Card
  lotCard: {
    backgroundColor: ADDIS_NOIR.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: ADDIS_NOIR.edge,
    overflow: 'hidden',
  },
  lotHeader: { padding: 20 },
  lotInfo: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  lotDetails: { flex: 1 },

  lotName: { color: '#FFF', fontSize: 18, fontFamily: Fonts.bold },
  lotLocation: { color: 'rgba(255,255,255,0.4)', fontSize: 12, marginTop: 4 },
  lotPricing: { alignItems: 'flex-end' },
  priceAmount: { color: ADDIS_NOIR.cyan, fontSize: 18, fontFamily: Fonts.bold },
  priceLabel: { color: 'rgba(255,255,255,0.3)', fontSize: 9, marginTop: 2 },
  availabilityBar: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  progressBar: { flex: 1, height: 4, backgroundColor: ADDIS_NOIR.lift, borderRadius: 2 },
  progressFill: { height: 4, borderRadius: 2 },
  availabilityText: { color: 'rgba(255,255,255,0.4)', fontSize: 10, fontFamily: Fonts.bold },

  // Spot Selection
  spotSelection: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: ADDIS_NOIR.edge,
    backgroundColor: ADDIS_NOIR.ink,
  },
  spotSelectionTitle: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 10,
    fontFamily: Fonts.bold,
    marginBottom: 16,
  },
  spotGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  spotButton: {
    width: (SCREEN_WIDTH - 92) / 6,
    aspectRatio: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  spotAvailable: { borderColor: ADDIS_NOIR.edge, backgroundColor: ADDIS_NOIR.surface },
  spotSelected: { borderColor: ADDIS_NOIR.cyan, backgroundColor: 'rgba(0, 245, 255, 0.1)' },
  spotOccupied: {
    borderColor: 'rgba(232, 49, 42, 0.2)',
    backgroundColor: 'rgba(232, 49, 42, 0.05)',
    opacity: 0.3,
  },
  spotText: { fontSize: 12, fontFamily: Fonts.bold },
  spotTextAvailable: { color: 'rgba(255,255,255,0.4)' },
  spotTextSelected: { color: ADDIS_NOIR.cyan },
  spotTextOccupied: { color: 'rgba(232, 49, 42, 0.4)' },
  spotLegend: { flexDirection: 'row', gap: 16, marginTop: 20 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendText: { color: 'rgba(255,255,255,0.3)', fontSize: 10, fontWeight: '700' },

  // Modals
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.9)' },
  modalContent: {
    backgroundColor: ADDIS_NOIR.surface,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 32,
    paddingBottom: 50,
  },
  modalTitle: { color: '#FFF', fontSize: 24, fontFamily: Fonts.bold, marginBottom: 8 },
  modalSubtitle: { color: 'rgba(255,255,255,0.4)', fontSize: 14, marginBottom: 24 },
  modalInfo: {
    backgroundColor: ADDIS_NOIR.lift,
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
    gap: 12,
  },
  modalButton: {
    backgroundColor: ADDIS_NOIR.cyan,
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
  },
  modalButtonText: { color: '#0B0D11', fontSize: 16, fontFamily: Fonts.bold },
  cancelButton: { marginTop: 12, paddingVertical: 12, alignItems: 'center' },
  cancelButtonText: { color: 'rgba(255,255,255,0.3)', fontSize: 14, fontWeight: '600' },

  // QR Modal
  qrModalContent: {
    backgroundColor: ADDIS_NOIR.surface,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 32,
    alignItems: 'center',
  },
  qrCard: { backgroundColor: '#FFF', padding: 24, borderRadius: 24, marginBottom: 24 },
  qrTitle: {
    color: '#000',
    fontSize: 12,
    fontFamily: Fonts.bold,
    marginBottom: 12,
    textAlign: 'center',
  },
  qrCode: { color: '#000', fontSize: 24, fontWeight: '800', textAlign: 'center' },
  qrDescription: {
    color: 'rgba(255,255,255,0.4)',
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 20,
  },
});
