import { StyleSheet } from 'react-native';
import { D, Radius, Fonts } from './StitchTheme';

export const styles = StyleSheet.create({
  // Image Upload Styles
  imagePickerContainer: { marginBottom: 20, alignItems: 'center' },
  imagePickerBtn: {
    width: '100%',
    height: 120,
    borderRadius: 16,
    backgroundColor: D.surface,
    borderStyle: 'dashed',
    borderWidth: 2,
    borderColor: D.blue + '40',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: D.blue + '15',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  imagePickerTxt: { color: D.sub, fontSize: 13, fontWeight: '500' },
  imagePreviewContainer: {
    width: '100%',
    height: 180,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: D.ink,
  },
  imagePreview: { width: '100%', height: '100%', resizeMode: 'cover' },
  removeImageBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: D.ink + 'CC',
    borderRadius: 12,
  },

  // Global Overrides
  container: { flex: 1, backgroundColor: D.ink },

  // Mobile Navbar
  navBarMobile: {
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: 'transparent',
    paddingTop: 10,
  },
  brandBoxMobile: { flexDirection: 'row', alignItems: 'center' },
  brandIconMobile: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: D.blue + '20',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: D.blue + '30',
  },
  brandNameMobile: { color: '#FFF', fontSize: 18, fontFamily: Fonts.headline },
  brandSubtitleMobile: {
    color: D.blue,
    fontSize: 9,
    fontFamily: Fonts.bold,
    letterSpacing: 1.5,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  navRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  navIconBtn: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: D.card,
    borderWidth: 1,
    borderColor: D.edge,
  },
  notifDot: {
    width: 8,
    height: 8,
    backgroundColor: '#FF3B30',
    borderRadius: 4,
    position: 'absolute',
    top: 6,
    right: 6,
    borderWidth: 2,
    borderColor: D.ink,
  },
  avatarBoxMobile: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: D.card,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: D.edge,
  },

  // Scrollable Mobile Tabs
  tabScrollWrap: {
    paddingVertical: 12,
    backgroundColor: 'transparent',
  },
  tabScroller: { paddingHorizontal: 16, gap: 10 },
  tabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 14,
    backgroundColor: D.card,
    borderWidth: 1,
    borderColor: D.edge,
  },
  tabItemActive: {
    backgroundColor: D.blue,
    borderColor: D.blue,
  },
  tabItemTxt: { color: D.sub, fontSize: 13, fontFamily: Fonts.bold, marginLeft: 8 },
  tabItemTxtActive: { color: '#00210F', fontFamily: Fonts.black },

  // Content Area
  mainScroll: { flex: 1 },
  tabContent: { padding: 16, paddingBottom: 100 },

  headerTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  pageTitle: { fontSize: 28, fontFamily: Fonts.black, color: D.text },
  pageSubtitle: { fontSize: 13, color: D.sub, marginTop: 4 },
  primaryButtonSolid: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: D.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: Radius.md,
  },
  iconButtonOutlined: {
    padding: 10,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: D.edge,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnTextThick: { fontSize: 13, fontFamily: Fonts.bold, marginLeft: 6, color: D.ink },

  cardTitle: { fontSize: 16, color: D.text, fontFamily: Fonts.bold },

  // Tab 1: Overview (Mobile)
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 24 },
  statCard: {
    flexBasis: '48%',
    flexGrow: 1,
    backgroundColor: D.lift,
    borderWidth: 1,
    borderColor: D.edge,
    borderRadius: Radius.card,
    padding: 16,
  },
  statIconBox: {
    width: 32,
    height: 32,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: { fontSize: 22, fontFamily: Fonts.black, color: D.text, marginBottom: 2 },
  statLabel: { fontSize: 11, color: D.sub, fontFamily: Fonts.bold },

  premiumStatCard: {
    flexBasis: '48%',
    flexGrow: 1,
    borderRadius: Radius.card,
    padding: 16,
    borderWidth: 1,
  },
  payoutChip: {
    alignSelf: 'flex-start',
    backgroundColor: D.primary + '15',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: Radius.sm,
    marginTop: 12,
  },
  payoutText: {
    fontSize: 10,
    color: D.primary,
    fontFamily: Fonts.bold,
  },
  miniStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: D.lift,
    padding: 16,
    borderRadius: Radius.card,
    borderWidth: 1,
    borderColor: D.edge,
    marginBottom: 24,
  },
  miniStat: {
    alignItems: 'center',
    flex: 1,
  },
  miniStatValue: {
    fontSize: 18,
    fontWeight: '700',
    color: D.text,
  },
  miniStatLabel: {
    fontSize: 9,
    color: D.sub,
    fontWeight: '700',
    letterSpacing: 1,
    marginTop: 4,
  },

  chartContainer: {
    backgroundColor: D.lift,
    borderWidth: 1,
    borderColor: D.edge,
    borderRadius: Radius.card,
    padding: 16,
    marginBottom: 24,
  },
  chartHeader: { marginBottom: 16 },
  chartGraphArea: {
    height: 140,
    flexDirection: 'row',
    alignItems: 'flex-end',
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderColor: D.edge,
    padding: 8,
  },
  chartBars: { flex: 1, flexDirection: 'row', justifyContent: 'space-around', height: 120 },
  chartCol: {
    width: 1,
    backgroundColor: 'transparent',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  chartBarLine: { width: 2, backgroundColor: D.primary, position: 'absolute', bottom: 0 },
  chartDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: D.primary,
    position: 'absolute',
  },
  chartDayLabel: {
    color: D.sub,
    fontSize: 8,
    marginTop: 8,
    textTransform: 'uppercase',
    position: 'absolute',
    bottom: -20,
  },

  topSellingContainer: {
    backgroundColor: D.lift,
    borderWidth: 1,
    borderColor: D.edge,
    borderRadius: Radius.card,
    padding: 16,
  },
  topSellingList: { marginTop: 16, gap: 16 },
  topSellingItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  tsImage: { width: 44, height: 44, borderRadius: 8, backgroundColor: D.rim },
  tsName: { fontSize: 13, fontWeight: '700', color: D.text },
  tsSales: { fontSize: 11, color: D.sub, marginTop: 4 },
  tsPrice: { fontSize: 13, color: D.primary, fontWeight: '700', fontFamily: 'monospace' },

  // Tab 2: Inventory (Mobile)
  filterRowMobile: { flexDirection: 'row', gap: 12, marginBottom: 20 },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: D.lift,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: D.edge,
  },
  searchInput: { flex: 1, marginLeft: 8, height: 40, color: D.text, fontSize: 13 },

  productMobileCard: {
    backgroundColor: D.lift,
    borderRadius: Radius.card,
    padding: 16,
    borderWidth: 1,
    borderColor: D.edge,
  },
  productMobileImg: { width: 56, height: 56, borderRadius: 8, backgroundColor: D.rim },
  tableSku: { fontSize: 11, color: D.sub },
  catBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: D.primary + '15',
  },
  catBadgeText: { fontSize: 9, color: D.primary, fontWeight: '700', letterSpacing: 0.5 },
  stockBarBgMob: {
    width: 60,
    height: 6,
    backgroundColor: D.rim,
    borderRadius: 3,
    overflow: 'hidden',
    marginLeft: 8,
  },
  stockBarFill: { height: '100%', borderRadius: 3 },
  stockText: { fontSize: 11, color: D.sub, fontWeight: '600' },

  // Tab 3: Orders (Mobile)
  alertBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: D.tertiary + '15',
    borderWidth: 1,
    borderColor: D.tertiary + '30',
    borderLeftWidth: 4,
    borderLeftColor: D.tertiary,
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
  },
  alertIconBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: D.tertiary + '20',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  alertTitle: { fontSize: 13, fontWeight: '700', color: D.tertiary, marginBottom: 2 },
  alertSub: { fontSize: 11, color: D.tertiary, opacity: 0.8 },

  orderMobileCard: {
    backgroundColor: D.lift,
    borderWidth: 1,
    borderColor: D.edge,
    borderRadius: Radius.card,
    padding: 16,
  },
  ocId: { fontSize: 12, color: D.text, fontFamily: 'monospace', fontWeight: '700' },
  ocTimeTxtMobile: { fontSize: 11, color: D.sub },
  ocStatusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  ocStatusTxt: { fontSize: 9, fontWeight: '700', letterSpacing: 0.5 },

  ocImgMobile: { width: 48, height: 48, borderRadius: 8, backgroundColor: D.rim },
  ocProdName: { fontSize: 13, fontWeight: '700', color: D.text },
  ocProdDetail: { fontSize: 11, color: D.sub, marginTop: 2, fontStyle: 'italic' },
  ocBigAmountMobile: { fontSize: 16, fontWeight: '700', color: D.primary, marginTop: 4 },

  ocDivider: { height: 1, backgroundColor: D.edge, marginVertical: 16 },

  ocTinyLabel: {
    fontSize: 9,
    color: D.sub,
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 4,
  },
  ocBuyerName: { fontSize: 12, fontWeight: '700', color: D.text },
  ocAddressTxt: { fontSize: 11, color: D.sub, marginTop: 2 },

  ocPinBoxMobile: {
    backgroundColor: D.surface,
    borderWidth: 1,
    borderColor: D.primary + '30',
    borderRadius: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    alignSelf: 'flex-start',
  },
  ocPinTxt: { color: D.primary, fontSize: 12, fontWeight: '700', letterSpacing: 2 },
  ocLockTxt: { color: D.secondary, fontSize: 12, fontWeight: '600', marginLeft: 4 },

  ocBtnMobile: {
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  ocBtnTxt: { color: D.ink, fontSize: 13, fontWeight: '700' },
  ocBtnMobileOutlined: {
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: D.edge,
  },
  ocBtnOutlinedTxtMobile: { color: D.sub, fontSize: 13, fontWeight: '600' },

  // Tab 4: Finance (Mobile)
  financeHeroMobile: {
    backgroundColor: D.primary,
    borderRadius: Radius.card,
    padding: 20,
    overflow: 'hidden',
  },
  fhLabel: { fontSize: 10, color: D.ink, opacity: 0.7, fontWeight: '700', letterSpacing: 1 },
  fhAmountMobile: { fontSize: 32, color: D.ink, fontWeight: '700', marginVertical: 8 },
  fhTrend: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.1)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  fhTrendTxt: { color: D.ink, fontSize: 11, fontWeight: '600', marginLeft: 6 },
  fhWithdrawBtn: {
    backgroundColor: D.ink,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  fhWithdrawTxt: { color: D.primary, fontSize: 12, fontWeight: '700' },

  txListMobile: {
    backgroundColor: D.lift,
    borderRadius: Radius.card,
    borderWidth: 1,
    borderColor: D.edge,
    padding: 16,
    gap: 16,
  },
  txItemMobile: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  txIconBoxMobile: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: D.rim,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tableName: { fontSize: 13, fontWeight: '700', color: D.text },
  txDateTxt: { fontSize: 11, color: D.sub, marginTop: 4 },
  tablePrice: { fontSize: 13, color: D.text, fontWeight: '700' },

  // New Modal Styles
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'flex-end' },
  modalContent: {
    backgroundColor: D.lift,
    borderTopLeftRadius: Radius.card,
    borderTopRightRadius: Radius.card,
    padding: 24,
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: { fontSize: 20, fontWeight: '700', color: D.text },
  formGroup: { marginBottom: 20 },
  inputLabel: {
    fontSize: 12,
    color: D.sub,
    fontWeight: '600',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  modalInput: {
    backgroundColor: D.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: D.edge,
    padding: 12,
    color: D.text,
    fontSize: 15,
  },
  smallBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: D.rim,
  },
  smallBadgeText: { fontSize: 12, color: D.text, fontWeight: '600' },
  submitBtn: {
    backgroundColor: D.primary,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  submitBtnText: { color: D.ink, fontSize: 16, fontWeight: '700' },
  deleteBtnSmall: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: D.rim,
    borderWidth: 1,
    borderColor: D.edge,
  },

  // Shipment Success Specific
  successCirc: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinDisplayCard: {
    backgroundColor: D.surface,
    borderWidth: 1,
    borderColor: D.primary + '30',
    borderRadius: Radius.card,
    padding: 24,
    marginTop: 24,
    width: '100%',
    alignItems: 'center',
  },
  pinTextLarge: { fontSize: 44, fontWeight: '800', color: D.primary, letterSpacing: 8 },
});
